version: "3.8"

services:
  # The name of the service to run
  vt-backend:
    build:
      # The path to the service's repository
      context: ./backend
      dockerfile: ./Dockerfile
    # bind the service's exposed port 80 to the host's 8222
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment: 
      - ROOT_PATH=/vt/backend
      - VOTING_SERVICE_PATH=host.docker.internal:8101/voting-service-api
    # export useful environment variables to the service's container
    # network_mode: host
    volumes:
      - ./public:/public

  vt:
    container_name: vt
    # image: nginx:alpine
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - vt-backend
    ports:
      #Port mapping:"Host OS port:container(Nginx)Port"
      - "8100:80"
    volumes:
      #volume mount:"Host OS path:Path in the container"
      - ./web/conf.d:/etc/nginx/conf.d
