version: "3.8"

services:
  # The name of the service to run
  vt-backend:
    build:
      # The path to the service's repository
      context: ./backend
      dockerfile: ./Dockerfile
    # bind the service's exposed port 80 to the host's 8222
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # export useful environment variables to the service's container
    # network_mode: host
    volumes:
      - ./public:/public

  vt:
    container_name: vt
    image: nginx:alpine
    depends_on:
      - vt-backend
    ports:
      #Port mapping:"Host OS port:container(Nginx)Port"
      - "81:80"
    volumes:
      #volume mount:"Host OS path:Path in the container"
      - ./web/conf.d:/etc/nginx/conf.d
      - ./frontend/public:/usr/share/nginx/html
      # - "C:/Users/neviem/tvoja/cesta/k/html/suborom:/usr/share/nginx/html"

  frontend-builder:
    container_name: frontend-builder
    build:
      context: ./frontend
      dockerfile: ./hot.dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
