version: "3.8"

services:
  vt-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    environment:
      - ROOT_PATH=/backend
      - VOTING_SERVICE_PATH=host.docker.internal:8080/voting-service-api
      - STATE_VECTOR_PATH=host.docker.internal:8080/statevector
      - VT_ONLY_DEV=1

  # frontend not needed for backend testing for now
  # vt:
  #   build:
  #     context: ./
  #     dockerfile: ./frontend/Dockerfile
  #   depends_on:
  #     - vt-backend
  #   ports:
  #     - "81:80"
