version: "3.8"

services:
  vt-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      - ROOT_PATH=/vt/backend
      - VOTING_SERVICE_PATH=host.docker.internal:8101/voting-service-api
      - STATE_VECTOR_PATH=host.docker.internal:8101/statevector
      - VOTING_PROCESS_MANAGER_PATH=host.docker.internal:8101/voting-process-manager-api

  vt:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - vt-backend
    ports:
      - "8100:80"
