version: "3.8"

services:
  # The name of the service to run
  vt-backend:
    build:
      # The path to the service's repository
      context: .
      dockerfile: ./Dockerfile
    # bind the service's exposed port 80 to the host's 8222
    ports:
      - 8079:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment: 
      - ROOT_PATH=/backend
      - VOTING_SERVICE_PATH=host.docker.internal/voting-service-api
    # export useful environment variables to the service's container
    # network_mode: host
    volumes:
      - ./public:/public
