name: VT Pipe

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  push:

  workflow_dispatch:

jobs:
  test-vt-backend:
    name: VT Backend Tests
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose -f docker-compose.test.backend.yml -p vt-test-backend up --build --exit-code-from vt-backend --renew-anon-volumes --force-recreate --remove-orphans

      - name: Docker cleanup
        run: docker-compose -f docker-compose.test.backend.yml -p vt-test-backend down

  stage:
    name: VT Stage on team server
    needs: test-vt-backend
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Build and Stage
        run: docker-compose -f docker-compose.stage.yml -p vt-deployment up -d --build --remove-orphans
