name: VT Stage

on:
  pull_request:
    branches: [ master ]
    types: [closed]

  push:
    branches: [ development, EV-121-road-to-monorepo ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: Check out code
        uses: actions/checkout@v2

      - name: List
        run: ls -lah

      - name: Docker-Compose
        run: docker-compose -f docker-compose.stage.yml -p vt-deployment up -d --build --remove-orphans
